name: pre-commit-auto-format

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.PAT }}
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.0
      continue-on-error: true
      with:
        extra_args: --all-files
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt
        toolchain: nightly
    - run: cargo fmt --all
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: pre-commit auto format
        branch: ${{ github.head_ref || github.event.pull_request.head.ref || github.ref_name }}
